id: 681196fe-1a54-4f06-8f2e-6d457cd0b35f
inputs:
- description: Salesforce Unique ID
  key: salesforceId
  playbookInputQuery: null
  required: true
  value: {}
- description: Permission Set Id
  key: permissionSetId
  playbookInputQuery: null
  required: true
  value: {}
- description: Email to notify about errors in the provisioning process.
  key: ITNotificationEmail
  playbookInputQuery: null
  required: true
  value: {}
name: Salesforce IAM - Assign Permission Sets
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e884b912-4d8e-4d06-8060-60e004ff40ec
      iscommand: false
      name: ""
      version: -1
    taskid: e884b912-4d8e-4d06-8060-60e004ff40ec
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      permission_set_id:
        simple: ${inputs.permissionSetId}
      user_id:
        simple: ${inputs.salesforceId}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Assigns a permission set for a user.
      id: 55329934-6ce9-41eb-89e0-30ce6ef93706
      iscommand: true
      name: Assign Permission Set
      script: '|||salesforce-assign-permission-set'
      type: regular
      version: -1
    taskid: 55329934-6ce9-41eb-89e0-30ce6ef93706
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: SalesforceAssignPermissionSet.success
          operator: isTrue
      label: "yes"
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ddb81d8f-6393-4e67-8d69-2f891e81b3a7
      iscommand: false
      name: Permission Set Assignment Success?
      type: condition
      version: -1
    taskid: ddb81d8f-6393-4e67-8d69-2f891e81b3a7
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5fe9931c-502b-4f96-8cda-c6dabb3cdda9
      iscommand: false
      name: End
      type: title
      version: -1
    taskid: 5fe9931c-502b-4f96-8cda-c6dabb3cdda9
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      htmlBody:
        simple: |-
          Failed to assign permission set for: ${incident.username} <br>
          Error Message: ${SalesforceAssignPermissionSet.errorMessage}<br>
          Error Code: ${SalesforceAssignPermissionSet.errorCode}
      subject:
        simple: '${incident.username}: Failed to assign SFDC Permission Set'
      to:
        complex:
          root: inputs.ITNotificationEmail
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends an email using EWS.
      id: 3085ff48-6f65-4ca4-83fa-7cea103e8cd1
      iscommand: true
      name: Send Email
      script: '|||send-mail'
      type: regular
      version: -1
    taskid: 3085ff48-6f65-4ca4-83fa-7cea103e8cd1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 545
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
