id: Get Original Email - EWS v2
version: -1
contentitemexportablefields:
  contentitemfields: {}
name: Get Original Email - EWS v2
description: |-
  Use this playbook to retrieve the original email in the thread (as eml file), when the reporting user forwarded the original email not as an attachment.

  You must have the necessary permissions in the EWS integration to execute global search: eDiscovery
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 5607d1c6-85b0-4181-8b10-bb3a5b113c6f
    type: start
    task:
      id: 5607d1c6-85b0-4181-8b10-bb3a5b113c6f
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 122.5,
          "y": 0
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 03f2c080-1995-42fc-82ce-16d474fb5438
    type: condition
    task:
      id: 03f2c080-1995-42fc-82ce-16d474fb5438
      version: -1
      name: Is EWS v2 enabled?
      description: |
        Verifies that there is an active instance of the EWS v2 integration enabled.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: EWS v2
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                    ignorecase: true
                accessor: brand
            iscontext: true
    view: |-
      {
        "position": {
          "x": 380,
          "y": 140
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: d2eca123-db35-4b27-88d8-a8b77ffd6784
    type: title
    task:
      id: d2eca123-db35-4b27-88d8-a8b77ffd6784
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 130,
          "y": 1560
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: b2617aaf-5e54-43f5-89fe-82fc78cd099b
    type: condition
    task:
      id: b2617aaf-5e54-43f5-89fe-82fc78cd099b
      version: -1
      name: Verify required inputs
      description: Verify that the required input values for retrieving the original
        email exists.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.InReplyTo
            iscontext: true
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.ThreadTopic
            iscontext: true
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.Mailbox
            iscontext: true
    view: |-
      {
        "position": {
          "x": -90,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 73922583-8522-44e5-8184-ec87d2d885f8
    type: regular
    task:
      id: 73922583-8522-44e5-8184-ec87d2d885f8
      version: -1
      name: Search for messages by Thread-Topic
      description: Retrieve all messages found in the thread of the forwarded email.
      script: EWS v2|||ews-search-mailbox
      type: regular
      iscommand: true
      brand: EWS v2
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      query:
        simple: subject:"${inputs.ThreadTopic}"
      selected-fields:
        simple: in_reply_to
      target-mailbox:
        complex:
          root: inputs.Mailbox
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 25f6439f-778f-45a5-841a-53efe77d590c
    type: condition
    task:
      id: 25f6439f-778f-45a5-841a-53efe77d590c
      version: -1
      name: Was a matching email found?
      description: Verify that an email object with a Message-Id that matches the
        InReplyTo ID of the forwarded email was found.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: EWSItem
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: EWSItem.messageId
                      iscontext: true
                    right:
                      value:
                        simple: inputs.InReplyTo
                      iscontext: true
                accessor: messageId
            iscontext: true
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1080
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: e1d0343e-4065-4023-8e1d-83574c7bffbf
    type: regular
    task:
      id: e1d0343e-4065-4023-8e1d-83574c7bffbf
      version: -1
      name: Set context
      description: Set email object to context.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      key:
        simple: EWSItem
      value:
        complex:
          root: EWS
          accessor: Items
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 505dea9c-4e0f-404d-858c-3a090e4f6df0
    type: regular
    task:
      id: 505dea9c-4e0f-404d-858c-3a090e4f6df0
      version: -1
      name: Get original email as eml
      description: Retrieves items by item ID and uploads it's content as eml file.
      script: EWS v2|||ews-get-items-as-eml
      type: regular
      iscommand: true
      brand: EWS v2
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      item-id:
        complex:
          root: EWSItem
          filters:
          - - operator: containsGeneral
              left:
                value:
                  simple: EWSItem.messageId
                iscontext: true
              right:
                value:
                  simple: inputs.InReplyTo
                iscontext: true
          accessor: itemId
      target-mailbox:
        complex:
          root: inputs.Mailbox
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -230,
          "y": 1300
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 8764cbb0-dd56-4095-8df2-e77035713e2e
    type: regular
    task:
      id: 8764cbb0-dd56-4095-8df2-e77035713e2e
      version: -1
      name: Delete old context
      description: Delete the email objects from context.
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      key:
        simple: EWS
      subplaybook:
        simple: "yes"
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1625,
        "width": 990,
        "x": -230,
        "y": 0
      }
    }
  }
inputs:
- key: Mailbox
  value:
    complex:
      root: incident
      accessor: emailfrom
  required: false
  description: Email address of the reporting user.
  playbookInputQuery:
- key: InReplyTo
  value:
    complex:
      root: incident.phishingreporteremailheaders
      filters:
      - - operator: isEqualString
          left:
            value:
              simple: incident.phishingreporteremailheaders.headername
            iscontext: true
          right:
            value:
              simple: In-Reply-To
      accessor: headervalue
  required: false
  description: The InReplyTo header in the forwarded email.
  playbookInputQuery:
- key: ThreadTopic
  value:
    complex:
      root: incident.phishingreporteremailheaders
      filters:
      - - operator: isEqualString
          left:
            value:
              simple: incident.phishingreporteremailheaders.headername
            iscontext: true
          right:
            value:
              simple: Thread-Topic
      accessor: headervalue
  required: false
  description: The ThreadTopic header in the forwarded email.
  playbookInputQuery:
outputs:
- contextPath: File
  description: The original email as eml file.
  type: unknown
tests:
- No tests (auto formatted)
fromversion: 6.1.0
