id: AutoFocusTagsFeed-test
name: AutoFocusTagsFeed-test
version: -1
fromversion: 6.0.0
starttaskid: '0'
tasks:
  '0':
    id: '0'
    taskid: '5db5221d-d993-409d-9657-47a497a55f78'
    type: start
    task:
      id: '5db5221d-d993-409d-9657-47a497a55f78'
      version: -1
      name: ''
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    view: '{"position": {"x": 50, "y": 50}}'
    note: false
    timertriggers: []
    ignoreworker: false
  '1':
    id: 1
    taskid: '9d078c9b-49bd-439f-b941-a1c11e390f59'
    type: regular
    task:
      id: '9d078c9b-49bd-439f-b941-a1c11e390f59'
      version: -1
      name: DeleteContext
      description: ''
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      all:
        simple: yes
    separatecontext: false
    view: '{"position": {"x": 50, "y": 200}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '2':
    id: 2
    taskid: '6db9fb8f-1e13-411a-8357-f2044aa61c7e'
    type: regular
    task:
      id: '6db9fb8f-1e13-411a-8357-f2044aa61c7e'
      version: -1
      name: autofocus-tags-feed-get-indicators
      description: ''
      script: AutoFocusTagsFeed|||autofocus-tags-feed-get-indicators
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '3'
    scriptarguments: {}
    separatecontext: false
    view: '{"position": {"x": 50, "y": 400}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '3':
    id: '3'
    taskid: '53073468-bf47-4851-90ca-103d46c2eb19'
    type: title
    task:
      id: '53073468-bf47-4851-90ca-103d46c2eb19'
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ''
      description: ''
    separatecontext: false
    view: '{"position": {"x": 50, "y": 600}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
view: '{"linkLabelsPosition": {}, "paper": {"dimensions": {"height": 200, "width":
  380, "x": 50, "y": 50}}}'
inputs: []
outputs: []
description: Test playbook for AutoFocus Tags Feed integration
