id: Get Original Email - Generic v2
version: -1
contentitemexportablefields:
  contentitemfields: {}
name: Get Original Email - Generic v2
description: |-
  Use this playbook to retrieve the original email in the thread, including headers and attahcments, when the reporting user forwarded the original email not as an attachment.

  You must have the necessary permissions in your email service to execute global search.

  - EWS: eDiscovery
  - Gmail: Google Apps Domain-Wide Delegation of Authority
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 6baf77d7-3f70-422a-83ce-93358e3cd5de
    type: start
    task:
      id: 6baf77d7-3f70-422a-83ce-93358e3cd5de
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -130,
          "y": -110
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: ecc651e4-02b6-4a33-83d6-e2cab8198ece
    type: title
    task:
      id: ecc651e4-02b6-4a33-83d6-e2cab8198ece
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -130,
          "y": 390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 647f49b4-7f53-4638-82d6-355feaf1ff11
    type: playbook
    task:
      id: 647f49b4-7f53-4638-82d6-355feaf1ff11
      version: -1
      name: Get Original Email - Gmail
      description: |
        Use this playbook to retrieve the original email in the thread, including headers and attahcments, when the reporting user forwarded the original email not as an attachment.

        You must have the necessary permissions in your Gmail service to execute global search: Google Apps Domain-Wide Delegation of Authority
      playbookName: Get Original Email - Gmail
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      EmailID:
        complex:
          root: inputs.MessageID
      From:
        complex:
          root: inputs.EmailFrom
          transformers:
          - operator: replaceMatch
            args:
              regex:
                value:
                  simple: (?i).*<([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,})>
              replaceWith:
                value:
                  simple: $1
      User:
        complex:
          root: inputs.EmailTo
          transformers:
          - operator: replaceMatch
            args:
              regex:
                value:
                  simple: (?i).*<([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,})>
              replaceWith:
                value:
                  simple: $1
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 250,
          "y": 190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 76628e90-084a-4f3d-86f3-ed9c8c64699c
    type: playbook
    task:
      id: 76628e90-084a-4f3d-86f3-ed9c8c64699c
      version: -1
      name: Get Original Email - EWS
      description: |-
        Use this playbook to retrieve the original email in the thread, including headers and attahcments, when the reporting user forwarded the original email not as an attachment.

        You must have the necessary permissions in the EWS integration to execute global search: eDiscovery
      playbookName: Get Original Email - EWS
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      InReplyTo:
        complex:
          root: inputs.InReplyTo
      Mailbox:
        complex:
          root: inputs.EmailFrom
      ThreadTopic:
        complex:
          root: inputs.ThreadTopic
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": -510,
          "y": 190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 52b63562-f591-4520-8e4f-caf3aef00bae
    type: title
    task:
      id: 52b63562-f591-4520-8e4f-caf3aef00bae
      version: -1
      name: Email Service Providers
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "6"
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -130,
          "y": 35
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 565,
        "width": 1140,
        "x": -510,
        "y": -110
      }
    }
  }
inputs:
- key: MessageID
  value:
    complex:
      root: incident
      accessor: apdinternalmessageid
      transformers:
      - operator: append
        args:
          item:
            value:
              simple: incident.emailmessageid
            iscontext: true
      - operator: append
        args:
          item:
            value:
              simple: incident.uuid
            iscontext: true
  required: false
  description: 'The Message ID of the email to retrieve. '
  playbookInputQuery:
- key: EmailFrom
  value:
    complex:
      root: incident
      accessor: emailfrom
  required: false
  description: Email address of the reporting user.
  playbookInputQuery:
- key: InReplyTo
  value:
    complex:
      root: incident.emailheaders
      filters:
      - - operator: isEqualString
          left:
            value:
              simple: incident.emailheaders.headername
            iscontext: true
          right:
            value:
              simple: In-Reply-To
      accessor: headervalue
  required: false
  description: The InReplyTo header in the forwarded email.
  playbookInputQuery:
- key: ThreadTopic
  value:
    complex:
      root: incident.emailheaders
      filters:
      - - operator: isEqualString
          left:
            value:
              simple: incident.emailheaders.headername
            iscontext: true
          right:
            value:
              simple: Thread-Topic
      accessor: headervalue
  required: false
  description: The ThreadTopic header in the forwarded email.
  playbookInputQuery:
- key: EmailTo
  value:
    complex:
      root: incident
      accessor: emailto
  required: false
  description: Email address of the reporting user.
  playbookInputQuery:
outputs:
- contextPath: Email
  description: The email object
  type: unknown
- contextPath: File
  description: Original attachments
  type: unknown
- contextPath: Email.To
  description: The recipient of the email
  type: string
- contextPath: Email.From
  description: The sender of the email
  type: string
- contextPath: Email.CC
  description: The CC address of the email
  type: string
- contextPath: Email.BCC
  description: The BCC address of the email
  type: string
- contextPath: Email.HTML
  description: The email HTML
  type: string
- contextPath: Email.Body
  description: The email text body
  type: string
- contextPath: Email.Headers
  description: The email headers
  type: unknown
- contextPath: Email.Subject
  description: The email subject
  type: string
- contextPath: Email.HeadersMap
  description: The headers of the email.
fromversion: 6.0.0
tests:
- Phishing v2 - Test - Incident Starter