id: ThreatStream-Test
version: -1
name: ThreatStream-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 9142f6d7-807e-4f13-8351-6672535148fa
    type: start
    task:
      id: 9142f6d7-807e-4f13-8351-6672535148fa
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 1e615377-76e4-4bf0-864d-fb26025f29d9
    type: regular
    task:
      id: 1e615377-76e4-4bf0-864d-fb26025f29d9
      version: -1
      name: Check Domain Reputation
      description: Checks the reputation of the domain name.
      script: Anomali ThreatStream v3|||domain
      type: regular
      iscommand: true
      brand: Anomali ThreatStream v3
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      domain:
        simple: y.gp
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: bf4ba0da-661b-400e-82b9-debadd531039
    type: condition
    task:
      id: bf4ba0da-661b-400e-82b9-debadd531039
      version: -1
      name: 'Validate  Domain Context '
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.Domain.Address
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.Domain.Severity
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 532106ea-9f87-4221-84b3-12e1ac3519e4
    type: regular
    task:
      id: 532106ea-9f87-4221-84b3-12e1ac3519e4
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
      - "7"
      - "5"
      - "9"
      - "11"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 2db874db-37aa-45a8-8edc-962d87b6d362
    type: regular
    task:
      id: 2db874db-37aa-45a8-8edc-962d87b6d362
      version: -1
      name: Check IP Reputation
      description: Checks the reputation of the given IP.
      script: Anomali ThreatStream v3|||ip
      type: regular
      iscommand: true
      brand: Anomali ThreatStream v3
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      ip:
        simple: 78.78.78.67
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 591136e6-2a0a-46f7-882c-15807e341822
    type: condition
    task:
      id: 591136e6-2a0a-46f7-882c-15807e341822
      version: -1
      name: Validate IP context
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: IP.Address
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.IP.Status
            iscontext: true
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: defd38dd-3c6c-493e-89e3-77c19d3a23d3
    type: regular
    task:
      id: defd38dd-3c6c-493e-89e3-77c19d3a23d3
      version: -1
      name: Check URL reputation
      description: Checks the reputation of the given URL.
      script: Anomali ThreatStream v3|||url
      type: regular
      iscommand: true
      brand: Anomali ThreatStream v3
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      url:
        simple: http://www.ujhy1.com/
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: e6cb05e5-53d6-488a-8f80-55df7471f636
    type: condition
    task:
      id: e6cb05e5-53d6-488a-8f80-55df7471f636
      version: -1
      name: Validate URL Reputation
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: URL.Data
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.URL.Status
            iscontext: true
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 555ff0c3-b6cd-4204-8af2-35b4e6c83bcd
    type: regular
    task:
      id: 555ff0c3-b6cd-4204-8af2-35b4e6c83bcd
      version: -1
      name: Check email reputation
      description: Checks the reputation of the given email address.
      script: Anomali ThreatStream v3|||threatstream-email-reputation
      type: regular
      iscommand: true
      brand: Anomali ThreatStream v3
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      email:
        simple: egov@ac.in
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: f6f12b98-7aa8-48a3-8ca7-ffdc8adb6d56
    type: condition
    task:
      id: f6f12b98-7aa8-48a3-8ca7-ffdc8adb6d56
      version: -1
      name: Validate Email Reputation
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.EmailReputation.Email
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.EmailReputation.Confidence
            iscontext: true
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: 90b5c6bc-7adf-4666-820b-d4c8d1e426ef
    type: regular
    task:
      id: 90b5c6bc-7adf-4666-820b-d4c8d1e426ef
      version: -1
      name: Check SHA256 reputation
      description: Checks the reputation of the given SHA256 of the file.
      script: Anomali ThreatStream v3|||file
      type: regular
      iscommand: true
      brand: Anomali ThreatStream v3
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      file:
        simple: 178ba564b39bd07577e974a9b677dfd86ffa1f1d0299dfd958eb883c5ef6c3e1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: a8a9b78c-2718-4cc2-873d-4b2b76fdfe4d
    type: condition
    task:
      id: a8a9b78c-2718-4cc2-873d-4b2b76fdfe4d
      version: -1
      name: Validate  File reputation
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: File.SHA256
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.File.Severity
            iscontext: true
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 8f374640-9a3e-49a8-80cb-a5e4e2371261
    type: regular
    task:
      id: 8f374640-9a3e-49a8-80cb-a5e4e2371261
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 4b023b7c-02de-4103-814e-8154f916b6ac
    type: title
    task:
      id: 4b023b7c-02de-4103-814e-8154f916b6ac
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: 03f5d9cd-a68a-48d0-85ff-3cd5fcf1bd75
    type: regular
    task:
      id: 03f5d9cd-a68a-48d0-85ff-3cd5fcf1bd75
      version: -1
      name: Get Indicator by ID
      description: Return filtered indicators from ThreatStream. If query is defined,
        it overides all othe arguments that were passed to the command.
      script: Anomali ThreatStream v3|||threatstream-get-indicators
      type: regular
      iscommand: true
      brand: Anomali ThreatStream v3
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      id:
        simple: "231017344"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: 316490d4-ac60-45c6-88c5-5cd18a5a4a84
    type: condition
    task:
      id: 316490d4-ac60-45c6-88c5-5cd18a5a4a84
      version: -1
      name: Validate Indicator Context
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "17"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ThreatStream.Indicators.Value
            iscontext: true
          right:
            value:
              simple: y.gp
      - - operator: isEqualString
          left:
            value:
              simple: ThreatStream.Indicators.Severity
            iscontext: true
          right:
            value:
              simple: very-high
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "17":
    id: "17"
    taskid: a452d599-b462-418e-827f-b04e2289facb
    type: regular
    task:
      id: a452d599-b462-418e-827f-b04e2289facb
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "18"
      - "20"
      - "22"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "18":
    id: "18"
    taskid: b1e56aa5-31e9-442a-8ce6-cf45068919e0
    type: regular
    task:
      id: b1e56aa5-31e9-442a-8ce6-cf45068919e0
      version: -1
      name: Get Actor list
      description: Returns a list of Threat Model.
      script: '|||threatstream-get-model-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      limit:
        simple: "1"
      model:
        simple: actor
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "19":
    id: "19"
    taskid: 3eaadf02-9952-4985-894a-b6e5feefc550
    type: regular
    task:
      id: 3eaadf02-9952-4985-894a-b6e5feefc550
      version: -1
      name: Get Indicator By Model Actor
      description: Returns a list of indecators associated with the specified model
        and model's id.
      script: Anomali ThreatStream v3|||threatstream-get-indicators-by-model
      type: regular
      iscommand: true
      brand: Anomali ThreatStream v3
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      id:
        simple: ${ThreatStream.List.ID}
      limit:
        simple: "1"
      model:
        simple: actor
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "20":
    id: "20"
    taskid: 0be289ab-4e5d-4d96-80bc-902f06f4bad4
    type: regular
    task:
      id: 0be289ab-4e5d-4d96-80bc-902f06f4bad4
      version: -1
      name: Get Passive DNS
      description: Returns enrichment data for Domain or IP for availabe observables.
      script: Anomali ThreatStream v3|||threatstream-get-passive-dns
      type: regular
      iscommand: true
      brand: Anomali ThreatStream v3
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      limit:
        simple: "1"
      type:
        simple: domain
      value:
        simple: eqouifax.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "21":
    id: "21"
    taskid: fc5263b7-65ac-455f-81a7-b07bd9e16dec
    type: condition
    task:
      id: fc5263b7-65ac-455f-81a7-b07bd9e16dec
      version: -1
      name: Validate Passive DNS Context
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "14"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.PassiveDNS.Domain
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.PassiveDNS.Ip
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.PassiveDNS.Rrtype
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.PassiveDNS.Source
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.PassiveDNS.FirstSeen
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.PassiveDNS.LastSeen
            iscontext: true
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "22":
    id: "22"
    taskid: e2f08e38-6a69-4ec9-87c8-c375d4a08a8f
    type: regular
    task:
      id: e2f08e38-6a69-4ec9-87c8-c375d4a08a8f
      version: -1
      name: Get Campaign List
      description: Returns a list of Threat Model.
      script: Anomali ThreatStream v3|||threatstream-get-model-list
      type: regular
      iscommand: true
      brand: Anomali ThreatStream v3
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      limit:
        simple: "1"
      model:
        simple: campaign
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "23":
    id: "23"
    taskid: ca8dcc22-5987-48c9-81ce-5e2e78a49015
    type: regular
    task:
      id: ca8dcc22-5987-48c9-81ce-5e2e78a49015
      version: -1
      name: Get Indicator By Model Campaing
      description: Returns a list of indecators associated with the specified model
        and model's id.
      script: Anomali ThreatStream v3|||threatstream-get-indicators-by-model
      type: regular
      iscommand: true
      brand: Anomali ThreatStream v3
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      id:
        simple: ${ThreatStream.List.ID}
      limit:
        simple: "1"
      model:
        simple: campaign
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1785,
        "width": 2100,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0
description: ''
