id: get_original_email_-_gmail
version: -1
contentitemexportablefields:
  contentitemfields: {}
name: Get Original Email - Gmail
description: |
  Use this playbook to retrieve the original email in the thread, including headers and attahcments, when the reporting user forwarded the original email not as an attachment.

  You must have the necessary permissions in your Gmail service to execute global search: Google Apps Domain-Wide Delegation of Authority
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: d8403573-b211-4d44-885c-a365045c61a2
    type: start
    task:
      id: d8403573-b211-4d44-885c-a365045c61a2
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 30,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 81842102-b7a7-4202-8319-54c4b8660756
    type: condition
    task:
      id: 81842102-b7a7-4202-8319-54c4b8660756
      version: -1
      name: Is Gmail enabled?
      description: |
        Verifies that there is an active instance of the Gmail integration enabled.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "17"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: Gmail
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                    ignorecase: true
                accessor: brand
            iscontext: true
    view: |-
      {
        "position": {
          "x": 30,
          "y": 360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 185c00fb-4375-4607-8b99-7538c88315bc
    type: title
    task:
      id: 185c00fb-4375-4607-8b99-7538c88315bc
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 30,
          "y": 2670
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: c9618262-b2ae-4c68-8985-c15ccd1cddcc
    type: regular
    task:
      id: c9618262-b2ae-4c68-8985-c15ccd1cddcc
      version: -1
      name: Retrieve the forwarded email from Gmail
      description: Get the data and metadata of the forwarded email from the Gmail
        service.
      script: Gmail|||gmail-get-mail
      type: regular
      iscommand: true
      brand: Gmail
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      message-id:
        complex:
          root: inputs.EmailID
          filters:
          - - operator: isExists
              left:
                value:
                  simple: inputs.EmailID
                iscontext: true
      user-id:
        complex:
          root: inputs.User
      user-key:
        complex:
          root: inputs.User
    reputationcalc: 2
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 240,
          "y": 760
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: ea7b5d02-8ad9-435f-849b-d8aa29f18cdc
    type: condition
    task:
      id: ea7b5d02-8ad9-435f-849b-d8aa29f18cdc
      version: -1
      name: Was the original email retrieved?
      description: Verify that there is a Gmail email object in the context.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: Gmail
                accessor: ID
            iscontext: true
    view: |-
      {
        "position": {
          "x": 240,
          "y": 925
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: d991707f-7216-470f-8fe1-789296389e46
    type: condition
    task:
      id: d991707f-7216-470f-8fe1-789296389e46
      version: -1
      name: Was the forwarded email data retrieved?
      description: Verify that the InReplyTo and Subject fields are in context.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: GmailSubject
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: InReplyTo
            iscontext: true
    view: |-
      {
        "position": {
          "x": 327.5,
          "y": 1624
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 51f995a7-86c8-41d8-8c3a-1640f2eae3a1
    type: regular
    task:
      id: 51f995a7-86c8-41d8-8c3a-1640f2eae3a1
      version: -1
      name: Set context
      description: Set the InReplyTo field to context.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      key:
        simple: InReplyTo
      value:
        simple: ${Gmail.Headers(val.Name == "In-Reply-To").Value}
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 327.5,
          "y": 1100
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: f29c9b52-e600-4055-8643-ae2dbf053c0d
    type: regular
    task:
      id: f29c9b52-e600-4055-8643-ae2dbf053c0d
      version: -1
      name: Search for original email
      description: Search Gmail for the original email.
      script: Gmail|||gmail-search
      type: regular
      iscommand: true
      brand: Gmail
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      subject:
        complex:
          root: GmailSubject
      user-id:
        complex:
          root: inputs.From
      user-key:
        complex:
          root: inputs.From
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 490,
          "y": 1920
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 0d98eed8-9fa5-416d-8027-ecb0179377a2
    type: regular
    task:
      id: 0d98eed8-9fa5-416d-8027-ecb0179377a2
      version: -1
      name: Set context
      description: Set the Subject field to context stripped of all prefixes.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      key:
        simple: GmailSubject
      value:
        complex:
          root: Gmail
          accessor: Subject
          transformers:
          - operator: replaceMatch
            args:
              regex:
                value:
                  simple: (?i)([\[\(] *)?(RE|FWD?) *([-:;)\]][ :;\])-]*|$)|\]+ *$
              replaceWith: {}
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 327.5,
          "y": 1275
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: bde00ff1-57ae-4fca-889e-fa28e6785f83
    type: regular
    task:
      id: bde00ff1-57ae-4fca-889e-fa28e6785f83
      version: -1
      name: Delete old context
      description: Delete the forwarded Gmail email object from context.
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      key:
        simple: Gmail
      subplaybook:
        simple: "yes"
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 327.5,
          "y": 1450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: a36b43f8-9e58-464e-81ce-724ed667baad
    type: regular
    task:
      id: a36b43f8-9e58-464e-81ce-724ed667baad
      version: -1
      name: Set context
      description: Set the original email to context.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
      - "15"
    scriptarguments:
      key:
        simple: OriginalEmail
      value:
        simple: ${.=val.Gmail.filter(g => g.Headers.filter(h => h.Name === "Message-ID"
          && h.Value == val.InReplyTo).length > 0)}
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 490,
          "y": 2290
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 934fbada-6a8c-44f9-89bf-071e1dc62be6
    type: regular
    task:
      id: 934fbada-6a8c-44f9-89bf-071e1dc62be6
      version: -1
      name: Get attachments of the original email
      description: Retrieve the attachments of the original email from Gmail.
      script: Gmail|||gmail-get-attachments
      type: regular
      iscommand: true
      brand: Gmail
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      message-id:
        complex:
          root: OriginalEmail
          accessor: ID
      user-id:
        complex:
          root: OriginalEmail
          accessor: Mailbox
      user-key:
        complex:
          root: OriginalEmail
          accessor: Mailbox
    reputationcalc: 2
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 277.5,
          "y": 2465
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 6f9d14e3-46ad-4d79-827c-65594858cc30
    type: condition
    task:
      id: 6f9d14e3-46ad-4d79-827c-65594858cc30
      version: -1
      name: Was the original email retrieved?
      description: Verify that the original email is in context (matched by the InReplyTo
        ID).
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "12"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: ${.=val.Gmail.filter(g => g.Headers.filter(h => h.Name === "Message-ID"
                && h.Value == val.InReplyTo).length > 0)}
    view: |-
      {
        "position": {
          "x": 490,
          "y": 2095
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: 70478489-d4d3-4fba-80d3-66e8069a0830
    type: regular
    task:
      id: 70478489-d4d3-4fba-80d3-66e8069a0830
      version: -1
      name: Set output
      description: Set the playbook outputs to context.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      key:
        simple: Email
      value:
        simple: '${OriginalEmail={Subject: val[''Subject''], To: val[''To''], From:
          val[''From''], Text: val[''Body''], HTML: val[''Html''], Headers: val[''Headers''],
          CC: val[''CC''], BCC: val[''BCC'']}}'
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 707.5,
          "y": 2465
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "17":
    id: "17"
    taskid: 7d487616-0bce-4a7d-8cf8-99e9cd08c48d
    type: condition
    task:
      id: 7d487616-0bce-4a7d-8cf8-99e9cd08c48d
      version: -1
      name: Verify Playbook Inputs
      description: Verify the playbook inputs.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.EmailID
            iscontext: true
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.User
            iscontext: true
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.From
            iscontext: true
    view: |-
      {
        "position": {
          "x": 240,
          "y": 580
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
system: true
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2525,
        "width": 1057.5,
        "x": 30,
        "y": 210
      }
    }
  }
inputs:
- key: EmailID
  value:
    complex:
      root: incident
      accessor: emailmessageid
  required: false
  description: Email ID of the forwarded message.
  playbookInputQuery:
- key: User
  value:
    complex:
      root: incident
      accessor: emailto
      transformers:
      - operator: replaceMatch
        args:
          regex:
            value:
              simple: (?i).*<([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,})>
          replaceWith:
            value:
              simple: $1
  required: false
  description: Email address of the reporting user.
  playbookInputQuery:
- key: From
  value:
    complex:
      root: incident
      accessor: emailfrom
      transformers:
      - operator: replaceMatch
        args:
          regex:
            value:
              simple: (?i).*<([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,})>
          replaceWith:
            value:
              simple: $1
  required: false
  description: Email address of the thread originator.
  playbookInputQuery:
outputs:
- contextPath: Email
  description: The email object
  type: unknown
- contextPath: Email.To
  description: The recipient of the email
  type: string
- contextPath: Email.From
  description: The sender of the email
  type: string
- contextPath: Email.CC
  description: The CC address of the email
  type: string
- contextPath: Email.BCC
  description: The BCC address of the email
  type: string
- contextPath: Email.HTML
  description: The email HTML
  type: string
- contextPath: Email.Body
  description: The email text body
  type: string
- contextPath: Email.Headers
  description: The email headers
  type: string
- contextPath: Email.Subject
  description: The email subject
  type: string
- contextPath: File
  description: Original attachments
  type: unknown
tests:
- No tests
fromversion: 5.0.0