id: get_original_email_-_gmail
version: -1
contentitemexportablefields:
  contentitemfields: {}
name: Get Original Email - Gmail
description: |
  Use this playbook to retrieve the original email in the thread, including headers and attahcments, when the reporting user forwarded the original email not as an attachment.

  You must have the necessary permissions in your Gmail service to execute global search: Google Apps Domain-Wide Delegation of Authority
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: d8403573-b211-4d44-885c-a365045c61a2
    type: start
    task:
      id: d8403573-b211-4d44-885c-a365045c61a2
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 122.5,
          "y": -240
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 81842102-b7a7-4202-8319-54c4b8660756
    type: condition
    task:
      id: 81842102-b7a7-4202-8319-54c4b8660756
      version: -1
      name: Is Gmail enabled?
      description: |
        Verifies that there is an active instance of the Gmail integration enabled.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "17"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: Gmail
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                    ignorecase: true
                accessor: brand
            iscontext: true
    view: |-
      {
        "position": {
          "x": 122.5,
          "y": -95
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 185c00fb-4375-4607-8b99-7538c88315bc
    type: title
    task:
      id: 185c00fb-4375-4607-8b99-7538c88315bc
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 40,
          "y": 2300
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 810c068d-4e12-4731-8107-83c030751df1
    type: regular
    task:
      id: 810c068d-4e12-4731-8107-83c030751df1
      version: -1
      name: Retrieve the forwarded email from Gmail
      description: Get the data and metadata of the forwarded email from the Gmail
        service.
      script: Gmail|||gmail-get-mail
      type: regular
      iscommand: true
      brand: Gmail
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      message-id:
        complex:
          root: inputs.EmailID
          filters:
          - - operator: isExists
              left:
                value:
                  simple: inputs.EmailID
                iscontext: true
      user-id:
        complex:
          root: inputs.User
      user-key:
        complex:
          root: inputs.User
    reputationcalc: 2
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 18de5315-16b2-4d5c-8a81-2c50623ea89d
    type: condition
    task:
      id: 18de5315-16b2-4d5c-8a81-2c50623ea89d
      version: -1
      name: Was the original email retrieved?
      description: Verify that there is a Gmail email object in the context.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: Gmail
                accessor: ID
            iscontext: true
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: c09ebecb-9dc8-4e00-8fe4-0dbf0cd27d32
    type: condition
    task:
      id: c09ebecb-9dc8-4e00-8fe4-0dbf0cd27d32
      version: -1
      name: Was the forwarded email data retrieved?
      description: Verify that the InReplyTo and Subject fields are in context.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "19"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: GmailSubject
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: InReplyTo
            iscontext: true
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 1244
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: ea86d0cc-f9dc-4496-812c-bd3f5c52d08c
    type: regular
    task:
      id: ea86d0cc-f9dc-4496-812c-bd3f5c52d08c
      version: -1
      name: Set context
      description: Set the InReplyTo field to context.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      key:
        simple: InReplyTo
      value:
        simple: ${Gmail.Headers(val.Name == "In-Reply-To").Value}
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: ead0502f-8bdf-4d43-849d-4de4023c7052
    type: regular
    task:
      id: ead0502f-8bdf-4d43-849d-4de4023c7052
      version: -1
      name: Search for original email
      description: Search Gmail for the original email.
      script: Gmail|||gmail-search
      type: regular
      iscommand: true
      brand: Gmail
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      after:
        complex:
          root: AfterDate
      subject:
        complex:
          root: GmailSubject
      user-id:
        complex:
          root: inputs.From
      user-key:
        complex:
          root: inputs.From
    reputationcalc: 2
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 4bf99d41-0f5c-4f08-8c98-785cb0e5503d
    type: regular
    task:
      id: 4bf99d41-0f5c-4f08-8c98-785cb0e5503d
      version: -1
      name: Set context
      description: Set the Subject field to context stripped of all prefixes.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      key:
        simple: GmailSubject
      value:
        complex:
          root: Gmail
          accessor: Subject
          transformers:
          - operator: replaceMatch
            args:
              regex:
                value:
                  simple: (?i)([\[\(] *)?(RE|FWD?) *([-:;)\]][ :;\])-]*|$)|\]+ *$
              replaceWith: {}
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 4dbd3cc6-ae7c-4de5-89d2-b3e1b47acec5
    type: regular
    task:
      id: 4dbd3cc6-ae7c-4de5-89d2-b3e1b47acec5
      version: -1
      name: Delete old context
      description: Delete the forwarded Gmail email object from context.
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      key:
        simple: Gmail
      subplaybook:
        simple: "yes"
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 7e75aef4-9998-407c-8ace-b342f3ef812f
    type: regular
    task:
      id: 7e75aef4-9998-407c-8ace-b342f3ef812f
      version: -1
      name: Set context
      description: Set the original email to context.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
      - "15"
    scriptarguments:
      key:
        simple: OriginalEmail
      value:
        simple: ${.=val.Gmail.filter(g => g.Headers.filter(h => h.Name === "Message-ID"
          && h.Value == val.InReplyTo).length > 0)}
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 590,
          "y": 1950
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 29868c31-fc31-4b25-8523-5a9c937af420
    type: regular
    task:
      id: 29868c31-fc31-4b25-8523-5a9c937af420
      version: -1
      name: Get attachments of the original email
      description: Retrieve the attachments of the original email from Gmail.
      script: Gmail|||gmail-get-attachments
      type: regular
      iscommand: true
      brand: Gmail
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      message-id:
        complex:
          root: OriginalEmail
          accessor: ID
      user-id:
        complex:
          root: OriginalEmail
          accessor: Mailbox
      user-key:
        complex:
          root: OriginalEmail
          accessor: Mailbox
    reputationcalc: 2
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 2125
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 0ce28338-abb6-4b8d-8155-3444a9df6ca9
    type: condition
    task:
      id: 0ce28338-abb6-4b8d-8155-3444a9df6ca9
      version: -1
      name: Was the original email retrieved?
      description: Verify that the original email is in context (matched by the InReplyTo
        ID).
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "12"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: ${.=val.Gmail.filter(g => g.Headers.filter(h => h.Name === "Message-ID"
                && h.Value == val.InReplyTo).length > 0)}
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1775
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: 8992e96c-4684-4e30-8b83-8a84274b9e7d
    type: regular
    task:
      id: 8992e96c-4684-4e30-8b83-8a84274b9e7d
      version: -1
      name: Set output
      description: Set the playbook outputs to context.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      key:
        simple: Email
      value:
        simple: '${OriginalEmail={Subject: val[''Subject''], To: val[''To''], From:
          val[''From''], Text: val[''Body''], HTML: val[''Html''], Headers: val[''Headers''],
          CC: val[''CC''], BCC: val[''BCC'']}}'
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 807.5,
          "y": 2125
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "17":
    id: "17"
    taskid: 7d487616-0bce-4a7d-8cf8-99e9cd08c48d
    type: condition
    task:
      id: 7d487616-0bce-4a7d-8cf8-99e9cd08c48d
      version: -1
      name: Verify Playbook Inputs
      description: Verify the playbook inputs.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.EmailID
            iscontext: true
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.User
            iscontext: true
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.From
            iscontext: true
    view: |-
      {
        "position": {
          "x": 265,
          "y": 180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "19":
    id: "19"
    taskid: 5c2fab18-f852-4293-8e48-91df60ba1b76
    type: regular
    task:
      id: 5c2fab18-f852-4293-8e48-91df60ba1b76
      version: -1
      name: Set AfterDate
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      key:
        simple: AfterDate
      value:
        complex:
          root: incident
          accessor: autime
          transformers:
          - operator: substring
            args:
              from:
                value:
                  simple: "0"
              to:
                value:
                  simple: "10"
          - operator: TimeStampToDate
          - operator: ModifyDateTime
            args:
              variation:
                value:
                  simple: inputs.SearchDays
                iscontext: true
          - operator: split
            args:
              delimiter:
                value:
                  simple: '-'
          - operator: Cut
            args:
              delimiter:
                value:
                  simple: T
              fields:
                value:
                  simple: "1"
          - operator: join
            args:
              separator:
                value:
                  simple: /
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1430
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
system: true
view: |-
  {
    "linkLabelsPosition": {
      "6_19_yes": 0.55
    },
    "paper": {
      "dimensions": {
        "height": 2605,
        "width": 1147.5,
        "x": 40,
        "y": -240
      }
    }
  }
inputs:
- key: EmailID
  value:
    complex:
      root: incident
      accessor: emailmessageid
  required: false
  description: Email ID of the forwarded message.
  playbookInputQuery:
- key: User
  value:
    complex:
      root: incident
      accessor: emailto
      transformers:
      - operator: replaceMatch
        args:
          regex:
            value:
              simple: (?i).*<([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,})>
          replaceWith:
            value:
              simple: $1
  required: false
  description: Email address of the reporting user.
  playbookInputQuery:
- key: From
  value:
    complex:
      root: incident
      accessor: emailfrom
      transformers:
      - operator: replaceMatch
        args:
          regex:
            value:
              simple: (?i).*<([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,})>
          replaceWith:
            value:
              simple: $1
  required: false
  description: Email address of the thread originator.
  playbookInputQuery:
- key: SearchDays
  value:
    simple: 7 Days
  required: true
  description: The number of days included in the email search.
  playbookInputQuery:
outputs:
- contextPath: Email
  description: The email object
  type: unknown
- contextPath: Email.To
  description: The recipient of the email
  type: string
- contextPath: Email.From
  description: The sender of the email
  type: string
- contextPath: Email.CC
  description: The CC address of the email
  type: string
- contextPath: Email.BCC
  description: The BCC address of the email
  type: string
- contextPath: Email.HTML
  description: The email HTML
  type: string
- contextPath: Email.Body
  description: The email text body
  type: string
- contextPath: Email.Headers
  description: The email headers
  type: string
- contextPath: Email.Subject
  description: The email subject
  type: string
- contextPath: File
  description: Original attachments
  type: unknown
tests:
- No tests (auto formatted)
fromversion: 5.0.0