name: Secrets Detection
on: push

jobs:
  secrets_detection:
    runs-on: ubuntu-latest
    if: github.repository == 'demisto/content'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          cd Utils/github_workflow_scripts
          pipenv install --dev
      - name: Run secrets detection
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
          echo "PR number is: ${{ github.event.pull_request.number }}"
          echo "Target branch name is: $BRANCH_NAME"
          echo "Run secrets detection for PR: $PR_NUMBER on branch: $BRANCH_NAME"
          cd Utils/github_workflow_scripts
